### ISSUE TITLE
The link to the dataset provided in the document seems to be problematic

### ISSUE THREAD

**Issue by cryline** [hardware-fab/DL-to-locate-COs-for-SCA#1]
Hello, I noticed that the link to the dataset for the AES encryption algorithm mentioned in the DATASET section of your open-source project doesn't seem to redirect properly; it still points to your project's homepage. I would like to inquire whether the dataset is indeed located on your project's homepage or if there's an issue with the link setup. I hope you can look into this matter.

**Comment by dade145** [comment]
Hello, we've just committed a new readme with the correct link.
Thank you for the feedback!
